# Generated by Django 4.2.2 on 2023-06-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.IntegerField()),
                ('size_code', models.CharField(max_length=120)),
                ('sort_order', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_id', models.IntegerField()),
                ('other_data', models.CharField(max_length=120)),
                ('Apparel_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignapp.apparel_size')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorid', models.IntegerField()),
                ('color_code', models.CharField(max_length=120)),
                ('color_name', models.CharField(max_length=120)),
                ('Productcolour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignapp.product_color')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('parent_category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=120)),
                ('product_Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignapp.product_categories')),
            ],
        ),
    ]
